version: "3.3"

services:
  db:
    network_mode: host
    image: "postgres:11"
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - PGDATA=/var/lib/postgresql/data/pgdata


  node-app:
    network_mode: host
    build: .
    env_file: .dev.env
    container_name: "node"
    ports:
      - 3001:3001
